---
- name: Create a new user and change the admin shell to advanced
  #/////////////////////////////////////////////////////////////////
  #Created by S. Tariq Ali.
  #There are no warrienties to this playbook implied or otherwise
  #Thoroughly test all code within a test lab before using it in the production environment
  #/////////////////////////////////////////////////////////////////
  hosts: legacy1

  gather_facts: false
  remote_user: admin
  #remote_user: root
  collections:
  - f5networks.f5_modules
  
  tasks:
  - name: Add the user 'johnd' as an admin
    f5networks.f5_modules.bigip_user:
      username_credential: johnd
      password_credential: password
      full_name: John Doe
      partition_access:
        - all:admin
      update_password: on_create
      state: present
      provider:
        server: lb.mydomain.com
        user: admin
        password: secret
    delegate_to: localhost
